<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.asint</groupId>
	<artifactId>asint_ais_backend-parent</artifactId>
	<version>${revision}</version>
	<packaging>pom</packaging>

	<name>asint_ais_backend parent</name>

	<properties>
		<!-- OUR VERSION -->
        <revision>0.18.0</revision>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

		<!-- DEPENDENCIES VERSION -->
		<jdk.version>17</jdk.version>
		<cds.services.version>3.8.0</cds.services.version>
		<spring.boot.version>3.3.1</spring.boot.version>
		<cds.install-cdsdk.version>8.7.1</cds.install-cdsdk.version>

		<node.url>https://nodejs.org/dist/</node.url>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

	<modules>
		<module>asint_ais_backend</module>
		<module>asint_ais_event_layer</module>
		<!-- <module>asint_ais_integration_test</module> -->
        <module>asint_ais_performance_test</module>
	</modules>

	<dependencyManagement>
		<dependencies>
			<!-- CDS SERVICES -->
			<dependency>
				<groupId>com.sap.cds</groupId>
				<artifactId>cds-services-bom</artifactId>
				<version>${cds.services.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>

			<!-- SPRING BOOT -->
			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-dependencies</artifactId>
				<version>${spring.boot.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>

			<!-- CDS SDK BOM -->
			<!-- Will stick to latest patch of v4 for Java 1.8 -->
			<dependency>
				<groupId>com.sap.cloud.sdk</groupId>
				<artifactId>sdk-bom</artifactId>
				<version>5.11.0</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>

			<!-- SAP Cloud SDK Cloud Platform Core -->
            <dependency>
              <groupId>com.sap.cloud.sdk</groupId>
              <artifactId>cloudplatform-core</artifactId>
             </dependency>

			 <dependency>
               <groupId>com.sap.xsa</groupId>
               <artifactId>xsa-core</artifactId>
			   <version>1.9.0</version>
             </dependency>

            <dependency>
              <groupId>com.sap.cds</groupId>
              <artifactId>cds-services-impl</artifactId>
              <version>${cds.services.version}</version>
            </dependency>
        </dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<!-- JAVA VERSION -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.10.1</version>
                <configuration>
                    <source>${jdk.version}</source>
                    <target>${jdk.version}</target>
                    <parameters>true</parameters>
                    <useIncrementalCompilation>true</useIncrementalCompilation>
                    <fork>true</fork>
                    <compilerArgs>
                        <arg>-J-Xms512m</arg>
                        <arg>-J-Xmx2400m</arg>
                    </compilerArgs>
                </configuration>
            </plugin>

			<!-- MAKE SPRING BOOT PLUGIN RUNNABLE FROM ROOT -->
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<version>${spring.boot.version}</version>
				<configuration>
					<skip>true</skip>
				</configuration>
			</plugin>

			<!-- POM FLATTENING FOR CI FRIENDLY VERSIONS -->
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>flatten-maven-plugin</artifactId>
				<version>1.2.7</version>
				<configuration>
					<updatePomFile>true</updatePomFile>
					<flattenMode>resolveCiFriendliesOnly</flattenMode>
				</configuration>
				<executions>
					<execution>
						<id>flatten</id>
						<phase>process-resources</phase>
						<goals>
							<goal>flatten</goal>
						</goals>
					</execution>
					<execution>
						<id>flatten.clean</id>
						<phase>clean</phase>
						<goals>
							<goal>clean</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

			<!-- PROJECT STRUCTURE CHECKS -->
			<plugin>
				<artifactId>maven-enforcer-plugin</artifactId>
				<version>3.5.0</version>
				<executions>
					<execution>
						<id>Project Structure Checks</id>
						<goals>
							<goal>enforce</goal>
						</goals>
						<configuration>
							<rules>
								<requireMavenVersion>
									<version>3.6.3</version>
								</requireMavenVersion>
								<requireJavaVersion>
									<version>${jdk.version}</version>
								</requireJavaVersion>
								<reactorModuleConvergence />
							</rules>
							<fail>true</fail>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>